services:
  postgres:
    container_name: postgres-sql-clone
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: chit_chat_hub
    volumes:
      - postgres:/data/postgres
    networks:
      - chit_chat_hub
    restart: unless-stopped

  keycloak:
    container_name: keycloak-clone
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - chit_chat_hub
    command:
      - "start-dev"

networks:
  chit_chat_hub:
    driver: bridge

volumes:
  postgres:
    driver: local